# Generated by Django 4.2 on 2023-05-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
