# Generated by Django 4.2 on 2023-05-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0005_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
    ]
