# Generated by Django 4.2 on 2023-05-08 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0007_manga_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='release',
            new_name='released',
        ),
    ]
