# Generated by Django 4.2 on 2023-05-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_slug'),
        ('manga', '0008_rename_release_manga_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='characters',
            field=models.ManyToManyField(blank=True, to='characters.character'),
        ),
    ]
