# Generated by Django 4.2 on 2023-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_slug'),
        ('manga', '0009_manga_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='manga.genre'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='characters', to='characters.character'),
        ),
    ]
