# Generated by Django 4.2 on 2023-05-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_manga_genres_alter_manga_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
