version: '3'
services:
    web:
        build:
            context: .
        ports:
            - '8000:8000'
        volumes:
            - .:/animegg
        command: python manage.py runserver 0.0.0.0:8000

    redis:
        image: redis:7.0.5-alpine
        ports:
            - '6379:6379'
