# Generated by Django 4.2 on 2023-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('subname', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='author_images')),
            ],
        ),
    ]
