# Generated by Django 4.2 on 2023-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0010_manga_genres_alter_manga_characters'),
        ('authors', '0002_alter_author_image_alter_author_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='manga',
            field=models.ManyToManyField(blank=True, to='manga.manga'),
        ),
    ]
