# Generated by Django 4.2 on 2023-05-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_genre_slug'),
        ('authors', '0003_author_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='anime',
            field=models.ManyToManyField(blank=True, to='catalog.anime'),
        ),
    ]
