# Generated by Django 4.2 on 2023-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Story', 'Story'), ('Drawning', 'Drawning')], default=('Story', 'Story'), max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='author',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, to='authors.responsibilities'),
        ),
    ]
