# Generated by Django 4.2 on 2023-05-09 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_responsibilities_alter_author_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Responsibilities',
            new_name='Responsibility',
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'verbose_name': 'Responsibility', 'verbose_name_plural': 'Responsibilities'},
        ),
    ]
