# Generated by Django 4.2 on 2023-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_alter_anime_main_characters'),
        ('characters', '0002_alter_character_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='anime',
            field=models.ManyToManyField(blank=True, related_name='anime', to='catalog.anime'),
        ),
    ]
