# Generated by Django 4.2 on 2023-05-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0040_anime_related_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('video_url', models.URLField()),
                ('episode_number', models.PositiveIntegerField()),
                ('anime', models.ManyToManyField(related_name='episodes', to='catalog.anime')),
            ],
        ),
    ]
