# Generated by Django 4.2 on 2023-05-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_commentlike'),
        ('video_player', '0003_alter_episode_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='anime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.anime'),
        ),
    ]
