# Generated by Django 4.2 on 2023-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_about_customuser_birthday_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('Not Specified', 'Not Specified'), ('Female', 'Female'), ('Male', 'Male')], default='Not Specified', max_length=15),
        ),
    ]
