# Generated by Django 4.2 on 2023-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_genre_anime_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
