# Generated by Django 4.2 on 2023-05-05 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_agerestrictions_anime_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='agerestrictions',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.agevalues'),
        ),
    ]
