# Generated by Django 4.2 on 2023-05-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_agevalues_agerestrictions_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeRestrictions',
            new_name='AgeRestriction',
        ),
        migrations.RenameModel(
            old_name='AgeValues',
            new_name='AgeValue',
        ),
    ]
