# Generated by Django 4.2 on 2023-05-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_value_agerestriction_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='age_restrictions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.agerestriction'),
        ),
    ]
