# Generated by Django 4.2 on 2023-05-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_anime_age_restrictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Released', 'Released'), ('Announcement', 'Announcement')], default=('Announcement', 'Announcement'), max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status'),
        ),
    ]
