# Generated by Django 4.2 on 2023-05-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_type_alter_status_options_alter_status_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='title',
            field=models.CharField(choices=[('TV Series', 'TV Series'), ('Movie', 'Movie'), ('OVA', 'OVA'), ('Special', 'Special')], default=('TV Series', 'TV Series'), max_length=10, unique=True),
        ),
    ]
