# Generated by Django 4.2 on 2023-05-05 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_originvalue_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.originvalue'),
        ),
        migrations.AlterField(
            model_name='originvalue',
            name='title',
            field=models.CharField(max_length=124, unique=True),
        ),
    ]
