# Generated by Django 4.2 on 2023-05-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_anime_origin_alter_originvalue_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='value',
        ),
        migrations.AddField(
            model_name='origin',
            name='title',
            field=models.CharField(default='', max_length=124, unique=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.origin'),
        ),
        migrations.DeleteModel(
            name='OriginValue',
        ),
    ]
