# Generated by Django 4.2 on 2023-05-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_remove_origin_value_origin_title_alter_anime_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, upload_to='anime_posters/'),
        ),
    ]
