# Generated by Django 4.2 on 2023-05-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_anime_main_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPAARating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(default='', max_length=4, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='mpaa_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.mpaarating'),
        ),
    ]
