# Generated by Django 4.2 on 2023-05-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_mpaarating_anime_mpaa_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpaarating',
            name='abbreviation',
            field=models.CharField(default='', max_length=5, unique=True),
        ),
    ]
