# Generated by Django 4.2 on 2023-05-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_genre_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anime_screenshots/')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.anime')),
            ],
        ),
    ]
