# Generated by Django 4.2 on 2023-05-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_slug'),
        ('catalog', '0024_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='main_characters',
            field=models.ManyToManyField(blank=True, related_name='anime_characters', to='characters.character'),
        ),
    ]
