# Generated by Django 4.2 on 2023-05-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_animebookmarklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animebookmarklist',
            name='title',
        ),
        migrations.AddField(
            model_name='animebookmarklist',
            name='list',
            field=models.CharField(choices=[('watched', 'Watched'), ('watching', 'Watching'), ('planned', 'Planned'), ('dropped', 'Dropped'), ('postponed', 'Postponed'), ('rewatching', 'Re-watching')], default=('watching', 'Watching'), max_length=50),
        ),
    ]
