# Generated by Django 4.2 on 2023-05-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_animeusercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeusercomment',
            name='anime',
        ),
        migrations.AddField(
            model_name='anime',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='anime_comments', to='catalog.animeusercomment'),
        ),
        migrations.AddField(
            model_name='animeusercomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
