# Generated by Django 4.2 on 2023-05-16 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0035_animeusercomment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, null=True)),
                ('text', models.TextField()),
                ('anime', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.anime')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.animeratingstar')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
