# Generated by Django 4.2 on 2023-05-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_animereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animebookmarklist',
            options={'verbose_name': 'Bookmark list', 'verbose_name_plural': 'Bookmark lists'},
        ),
        migrations.AlterModelOptions(
            name='animereview',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='animeusercomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
