# Generated by Django 4.2 on 2023-05-18 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_alter_animebookmarklist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animerating',
            name='anime',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='anime_ratings', to='catalog.anime'),
        ),
    ]
