# Generated by Django 4.2 on 2023-05-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_anime_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='related_anime',
            field=models.ManyToManyField(blank=True, to='catalog.anime'),
        ),
    ]
