# Generated by Django 4.2 on 2023-05-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeusercomment',
            name='likes',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.commentlike'),
        ),
    ]
