# Generated by Django 4.2 on 2023-05-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_animeusercomment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeusercomment',
            name='likes',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.commentlike'),
        ),
    ]
