# Generated by Django 4.2 on 2023-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_animeusercomment_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
